[package]
name = "linker-trace"
version.workspace = true
edition = "2021"
repository.workspace = true

[dependencies]
anyhow = "1.0.93"
postcard = { version = "1.0.10", features = ["use-std"] }
serde = { version = "1.0.215", features = ["derive"] }

[lints]
workspace = true
