[package]
name = "linker-layout"
version.workspace = true
edition = "2021"
repository.workspace = true

[dependencies]
anyhow = "1.0.94"
postcard = { version = "1.1.1", features = ["use-std"] }
serde = { version = "1.0.215", features = ["derive"] }

[lints]
workspace = true
